### ISSUE TITLE
Some issues on test data

### ISSUE THREAD

**Issue by teruyukimorimura** [siteadmin/pdti#23]
Entries in ou=HcRegulatedOrganization
  - objectClass: uidObject is not specified.

Entry on hpdMemberId=3,ou=HPDProviderMembership
  - hpdHasAProvider attribute is required, but it's not specified.
    (Table 3.58.4.1.2.2.1-4: HPDProviderMembership Mandatory Attributes)

**Comment by Plow74** [comment]
Thanks for the input. The schema and test data have been updated per your findings. These will be available in the next release.

**Comment by Plow74** [comment]
New version of PDTI server was released and master branch has been updated. Thanks again for the input.
